import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import Banner from '@/Components/banner'
import Card from '@/Components/Card'
import coffeeStores from '../data/coffee-stores.json'

const inter = Inter({ subsets: ['latin'] })

export function getStaticProps(context) {
  
  return {
    props:
      { coffeeStores }
  }
}


export default function Home({coffeeStores}) {
 
  const handleBannerBtnClick = () => {
    console.log('banner btn clicked')
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>    
        <Banner buttonText="View Store nearby" handleBtnClick={handleBannerBtnClick} />
        <div className={styles.heroImage}> 

          <Image src='/static/hero-image.png' width={700} height={400} />
          {coffeeStores.length > 0 && (
            <>
              <h2 className={styles.heading2}>
                Toronto Stores
              </h2>
              <div className={styles.cardLayout}>
                {coffeeStores.map((store) => (<Card
                  key={store.id}
                  name={store.name}
                  imgUrl={store.imgUrl}
                  href={`/coffee-store/${store.id}`}
                  className={styles.card}
                  />))}
              </div>
            </>
          )}
        </div>
      </main>
    </div>
  )
}
